Guess movie poster link from event description
meo84/cinemapp pull request #2
Opened 2017-04-17 12:28 UTC by meo84

-- What? 
Simplify the form that creates a new movie: when the user selects a meetup event in the form, the link of the movie poster in the form is automatically filled out. 

-- How? 
I used an AJAX call on the `/movies/new` page, but wasn't sure how to test the call itself/the view, so only did some unit tests on the methods I used from the `Event` model to support the call (`.summary`, `#preview`, `#image_urls`, `#first_image_url`).

-- Questions?
If you have some suggestions on how I could test the AJAX call, or some feedback on the call itself and the other tests, they'll all be welcome!

2017-04-18 21:40 UTC, yaf requested changes
I think you must remove Gem version number of your Gemfile, and change some stuff around you Ajax call.

2017-04-18 21:40 UTC, yaf commented on Gemfile
> +gem 'nokogiri', '~>1.6.8'
Add gem versions in `Gemfile` seems a duplication with `Gemfile.lock`. Not a good idea. Remove them until they are absolutly necessary.

2017-04-18 21:40 UTC, yaf commented on Gemfile
> +  gem 'factory_girl_rails', '~>4.8.0'
Same here about Gem version number

2017-04-18 21:40 UTC, yaf commented on app/assets/javascripts/movies.js
> +  $('html').on('change', 'select#movie_event_ids.chosen', function(){
I don't look at your app in production, but `change` event could be fired a lot (focus on select field, use keyboard arrow, on worst, slide with pad...). Maybe a little button or a timer could help ?

2017-04-18 21:40 UTC, yaf commented on app/assets/javascripts/movies.js
> +      },
Often, `get` ajax call return a piece of html that you could use to change a piece of your DOM... Could it be a better idea here ?

2017-04-20 15:36 UTC, meo84 commented on Gemfile
> +gem 'nokogiri', '~>1.6.8'
When I remove the gem's version numbers from the Gemfile and run `bundle install`, it also removes the gem's version numbers from the Gemfile.lock. How can I know the versions I used later on?

2017-04-20 15:48 UTC, meo84 commented on app/assets/javascripts/movies.js
> +  $('html').on('change', 'select#movie_event_ids.chosen', function(){
I'm not sure I understand, I used event delegation with the [.on](https://api.jquery.com/on/) method to make sure the `change` event is only fired when the `select#movie_event_ids.chosen` element is changed. 
Can the event be fired even if I don't see requests on the network console?

2017-04-20 17:59 UTC, yaf commented on Gemfile
> +gem 'nokogiri', '~>1.6.8'
I don't think so, `Gemfile.lock` keep version of each installed gem.

2017-04-20 18:03 UTC, yaf commented on app/assets/javascripts/movies.js
> +  $('html').on('change', 'select#movie_event_ids.chosen', function(){
Try to scroll over your select box and look if your JavaScript keep calm or become mad

2017-04-20 23:24 UTC, meo84 commented on Gemfile
> +gem 'nokogiri', '~>1.6.8'
Thanks, you're right, I read it too fast and jumped to the dependencies section 🙊

2017-04-20 23:26 UTC, meo84 commented on app/assets/javascripts/movies.js
> +  $('html').on('change', 'select#movie_event_ids.chosen', function(){
JS seems to be keeping zen :)

2017-04-20 23:26 UTC, meo84 commented on app/assets/javascripts/movies.js
> +      },
Good idea, thanks!

2017-04-21 21:18 UTC, yaf approved these changes

2017-04-21 22:23 UTC, merged