Add user authentication and authorization
meo84/cinemapp pull request #3
Opened 2017-04-27 15:50 UTC by meo84

-- What? 
So far my application mixed public and admin pages, without the notion of user access. As I want to deploy the app and get started on continuous integration (\o/), I included a login system to authenticate users and give them access to admin pages if allowed. 
_Note_ There is no signup system as the only users are admin users (the app is only meant to be "viewed" by visitors)

-- How? 
I did the authentication and authorization process manually (secured the password with bcrypt) to understand it before using gems like devise and pundit. 
For the integration tests, I used Capybara with RSpec. 

-- Questions?

- I only setup the integration tests for the authentication process, this way I'll apply any feedback you have on the setup to the tests for the authorization process. In particular, would you use a db seed to create the admin user? 
- At first I was hesitant about creating a User model, since there will only ever be two admin users at most, but couldn't think of another approach. Do you have other approaches in mind that could be more relevant? 
- Any other suggestions welcome :)

2017-04-27 20:15 UTC, yaf reviewed
Don't git add auto-generate coffee files

2017-04-27 20:16 UTC, yaf reviewed
Don't add scss auto-generate files

2017-04-27 20:23 UTC, yaf requested changes
Some stuff to remove (important part)
And to get a better code, `extract method` from controller to model (or an other object)

2017-04-27 20:23 UTC, yaf commented on app/controllers/directors_controller.rb
> +    @directors_podium = [ Director.rank_by_movie_nb(1), Director.rank_by_movie_nb(2), Director.rank_by_movie_nb(3) ]
Perhaps this array could be return by a other file  :-)

2017-04-27 20:23 UTC, yaf commented on app/controllers/welcome_controller.rb
> +    @movies_podium = [ Movie.rank_by_attendance(1), Movie.rank_by_attendance(2), Movie.rank_by_attendance(3)]
Same as for director, this podium could be move (and test) easily in a method of an other object

2017-04-27 20:23 UTC, yaf commented on app/helpers/users_helper.rb
> +module UsersHelper
Don't add Generate empty helper

2017-04-27 20:23 UTC, yaf commented on spec/helpers/sessions_helper_spec.rb
> +require 'rails_helper'
Remove this generate empty file :-)

2017-04-27 20:23 UTC, yaf commented on spec/views/sessions/new.html.erb_spec.rb
> +require 'rails_helper'
Remove this generate empty file

2017-04-27 20:23 UTC, yaf commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
Remove this empty file

2017-04-27 20:23 UTC, yaf commented on app/assets/stylesheets/sessions.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
Remove this empty file

2017-04-27 20:23 UTC, yaf commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
Remove this empty file

2017-05-01 21:07 UTC, yaf approved these changes
Il ne manque plus que des tests sur le sessionHelper :-)

2017-05-01 21:07 UTC, yaf commented on app/controllers/welcome_controller.rb
> +    @movies_podium = Movie.most_attended(3)
:+1:

2017-05-01 21:07 UTC, yaf commented on app/helpers/sessions_helper.rb
> +module SessionsHelper
:+1:

2017-05-11 21:08 UTC, yaf requested changes
To approve, I hope to see better impl of `most_attended` and clean test code (without `delete_all`)

2017-05-11 21:08 UTC, yaf commented on app/models/movie.rb
> +    return [] if all.count == 0
It works, but you probably can do a better job here :-)

2017-05-11 21:08 UTC, yaf commented on spec/models/movie_spec.rb
> +        Movie.delete_all
Interesting caution, but it should not be necessary (otherwise, there is a worry I think).

2017-05-13 20:54 UTC, yaf approved these changes
:+1: :shipit:

2017-05-17 20:20 UTC, merged

2017-05-17 20:21 UTC, meo84 commented
Thank you for the review! 👍